name: Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
